//Auth
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_PERMISSIONS = 'LOGIN_USER_PERMISSIONS';

//App
export const ROLE_SELECTED = 'ROLE_SELECTED';
export const PROCESS_SELECTED = 'PROCESS_SELECTED';
export const FILE_SELECTED = 'FILE_SELECTED';